services:
  db:
    image: postgres:14.7-alpine
    container_name: 'formoku-db-local'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./database/localsetup:/docker-entrypoint-initdb.d
      - postgres_volume_formoku:/var/lib/postgresql/data
    networks:
      - app-network
  gyazo:
    build:
      context: ./localgyazo
      dockerfile: Dockerfile
    container_name: 'gyazo-local'
    ports:
      - '8888:80'
    environment:
      - GYAZO_API_TOKEN=sampletoken
    volumes:
      - gyazo_data_formoku:/var/www/html/data
      - gyazo_db_formoku:/var/www/html/db
    networks:
      - app-network

volumes:
  postgres_volume_formoku:
  gyazo_data_formoku:
  gyazo_db_formoku:

networks:
  app-network:
    driver: bridge